version: '1.0.{build}'

image: 
  - Visual Studio 2017
  - Ubuntu
platform:
  - x64
  - Win32
configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

build_script:
  - ps: ci/build.ps1

test_script:
  - ps: ci/test.ps1