version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
  - Win32
configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

before_build:
  - ci\appveyor\build.cmd

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).project.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\build\build\%CONFIGURATION%\unit_tests.exe'