version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
  - Win32
configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

build_script:
  - cmd: ci\windows\build.cmd

test_script:
  - cmd: ci\windows\test.cmd'%APPVEYOR_BUILD_FOLDER%\build\build\%CONFIGURATION%\unit_tests.exe'