version: '1.0.{build}'

image: 
  - Visual Studio 2017
  - Ubuntu1804
platform:
  - x64
  - Win32
configuration:
  - Release
  - Debug 

matrix:
  exclude:
    - image: Ubuntu
      platform: Win32

for:
-
  matrix:
    only:
      - image: Ubuntu
      
  environment:
    matrix:
      - cxx_compiler: gcc
      - cxx_compiler: clang

install:
  - git submodule update --init --recursive

build_script:
  - ps: ci/build.ps1

test_script:
  - ps: ci/test.ps1