version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
  - Win32
configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - ps: if($env:PLATFORM -eq 'x64') {'x64'; cmake .. -G "Visual Studio 15 2017 Win64"} else {'x86'; cmake .. -G "Visual Studio 15 2017"} 

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).project.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\build\build\%CONFIGURATION%\unit.tests.exe'