#ifndef UNIT_TESTS_MACROSES_HPP
#define UNIT_TESTS_MACROSES_HPP
	#ifdef USE_ALL_TESTS
		#define USE_SLOW_TESTS 
		#define USE_UTILS_TESTS 
		#define USE_HELPERS_TESTS
	#endif // USE_ALL_TESTS
#endif 
